version: '3.9'
services:
  movies:
    image: ganesh09876/life:v1
    ports:
      - "84:80"
    deploy:
      replicas: 3
    movies:
      image: ganesh09876/devops:v2
      ports:
        - "85:80"
      deploy:
        replicas: 3
    recharge:
      image: ganesh09876/aws:v3
      ports:
        - "86:80"
      deploy:
        replicas: 3
    paytm:
      image: ganesh09876/paytm:v4
      ports:
        - "87:80"
      deploy:
        replicas: 3

